config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root "events#index" 
resources :users, only: [:new, :create, :show, :edit, :index]
resources :sessions, only: [:new, :create, :destroy]
resources :events, only: [:index, :new, :create, :show]
get '/login', to: 'sessions#new' 
get '/sign_up', to: 'users#new' 
get '/logout', to: 'sessions#destroy'
post 'attend', to: 'events#attend_event'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, :description, :location, :date_time, presence: true
  belongs_to :creator, class_name: 'User'

  has_many :invitations
  has_many :attendees, through: :invitations, source: :user

  scope :past, -> { where 'date_time < ?', Date.today }
  scope :upcoming, -> { where 'date_time >= ?', Date.today }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, :last_name, presence: true
  validates :email, :username, presence: true, uniqueness: true
  has_many :events, foreign_key: 'creator_id'
  has_many :invitations
  has_many :attended_events, through: :invitations, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :already_logged_in?, :already_attendee?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def already_logged_in?
    current_user
  end

  def require_login
    redirect_to root_path unless already_logged_in?
  end

  def already_attendee?
    attendees = @event.attendees
    attendees.include?(current_user)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update attend_event destroy]
  before_action :require_login, only: %i[new create edit update destroy attend_event]

  def index
    @events = Event.all
    @upcoming_events = Event.upcoming
    @past_events = Event.past
  end

  def show
    @attendees = @event.attendees
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  def edit; end

  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def attend_event
    if !already_attendee?
      @event.attendees << current_user
      redirect_back fallback_location: :back
      flash[:notice] = 'Success! you have been registered to attend'
    else
      redirect_back fallback_location: :back
      flash[:notice] = 'You are an attendee. You can only register once!'
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:title, :description, :location, :date_time)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by_email(params[:email])

    if user
      session[:user_id] = user.id
      redirect_to user_path(user), notice: 'Logged in'
    else
      flash.now[:alert] = 'email does not exist'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: 'You have been logged out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :already_logged_in?, only: %i[show edit update destroy]

  def index
    @all_users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'Acount creation was successfull' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: unprocessable_entity }
      end
    end
  end

  def show
    @this_user = User.find(params[:id])
    @events = @this_user.events
    @attended_events = @this_user.attended_events
    @upcoming_events = @this_user.events.upcoming
    @past_events = @this_user.events.past
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def top_links
    if session[:user_id]
      "<a class=\"menu-item btn btn-primary\" href=\"#\"> Hello! #{current_user.first_name} </a>
            <a class=\"menu-item\" href=\"/users\"> <b> View all users</b> </a>
            <a class=\"menu-item\" href=\"/events\"> <b>See all events</b> </a>
             <a id=\"logout\"  class=\"menu-item\" href=\"/logout\">Logout  </a>".html_safe
    else
      "<a id=\"login\" class=\"menu-item\" href=\"/login\"> Login </a>
            <a class=\"menu-item\" href=\"/sign_up\">Create account  </a>".html_safe
    end
  end

  def add_event_btn
    '<a class="add_event" href="/events/new"> ADD EVENT</a>'.html_safe unless current_page?(new_event_path)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def show_error
    return unless @user.errors.any?

    error_list = ''
    @user.errors.full_messages.each do |error|
      error_list << "<li>#{error}</li>"
    end
  end
end

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class = "text-center">Events</h1>
<h3 class = "text-center">Upcoming Events</h3>

<div class = "row">
    
    <% @upcoming_events.each do |event| %>
      <div class = "col-md-3 mt-3 mb-3">
        <div class="card-deck">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Event Title: <%= event.title %></h5>
              <p class="card-text">Event: <%= event.description %></p>
              <p>Event Date: <%= event.date_time %></p>
            </div>
            <div class="card-footer">
              <%= link_to 'Attend this event', { :controller => 'events', :action => 'attend_event', :id => event.id }, method: :post, class: 'btn btn-default'%>
              <%= link_to 'Show', event, class: "btn btn-default" %>
            </div>
          </div>
        </div> 
    </div>
    <% end %> 

</div>
<hr>
<h3 class = "text-center">Past Events</h3>
<div class = "row">
    
    <% @past_events.each do |event| %>
      <div class = "col-md-3 mt-3 mb-3">
        <div class="card-deck">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Event Title: <%= event.title %></h5>
              <p class="card-text">Event: <%= event.description %></p>
              <p>Event Date: <%= event.date_time %></p>
            </div>
            <div class="card-footer">
              <%= link_to 'Show', event, class: "btn btn-default" %>
            </div>
          </div>
        </div> 
    </div>
    <% end %> 

</div>

app/views/events/new.html.erb
<div class="row">
<div class="col-md-6 offset-md-3 mt-5">
<%= form_with id: 'create-user-form', model: @event do |form|%>
<h1> Create event </h1>
<%= form.text_field :title, placeholder: 'Enter title of event' %>
<%= form.text_area :description, placeholder: 'Enter description of event'%>
<%= form.text_field :location, placeholder: 'Enter event location'%>
<%= form.datetime_select :date_time %> <br/>
<%= form.submit id: 'create_event', class:'btn btn-primary mt-3' %><br/>
<% end %>

</div>
</div>

app/views/events/show.html.erb
<div class="container-fluid">
<div class="row">
<div class="col-md-6 offset-md-3 mt-5">

<p id="notice"><%= notice %></p>
<br>
<hr>
<p>
  <h3>Events Creator: <%= @event.creator.username %></h3>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date_time %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>
<br>
<hr>
<p>
  <h3>Events Attendees</h3>

  <% @attendees.each do |attendee| %>
    <%= attendee.username %>
  <% end %>
</p>



<%= link_to 'Back', events_path %>

</ul>
 <div>
<div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
 
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#"> <b>&nbsp;&nbsp;PRIVATE EVENTS</b> </a>
 
    
        <div class="menu">
        <%= top_links %>
          
          <a class="menu-item" href="#"> &nbsp; </a>
        </div>
     
 
</nav>
    <%= yield %>
 <%= add_event_btn if already_logged_in?%>
  </body>
</html>

app/views/users/index.html.erb
<div class="container-fluid">
<div class="row">
<div class="col-md-6 offset-md-3 mt-5">
<ul class="list-group">
 <% @all_users.each do |person| %>
  <li class="list-group-item"> 
    <%= link_to "#{person.first_name} #{person.last_name}", user_path(person)%> 
  </li>
 <% end %>

</ul>
 <div>
<div>
 </div>

app/views/users/new.html.erb
<div class="row">
<div class="col-md-6 offset-md-3 mt-5">
<%= show_error %>
<%= form_with id: 'create-user-form', model: @user do |form|%>
<h1> Create account </h1>
<%= form.text_field :username, placeholder: 'Enter a chosen Username' %>
<%= form.text_field :first_name, placeholder: 'Enter first name'%>
<%= form.text_field :last_name, placeholder: 'Enter a last name'%>
<%= form.text_field :email, placeholder: 'Enter your email'%>
<%= form.submit id: 'create_user', class:'btn btn-primary mt-3' %><br/>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">

<p id="notice"><%= notice %></p>

<p>
    <h2>User Datails:</h2>  
</p>

<p>
  <strong>Name:</strong>
  <%= @this_user.first_name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @this_user.username %> 
</p>

<br>
<p>
    <h3>Created Events:</h3>
  </p>
<% @events.each do |event| %>
  
  <p>
    <strong>Description:</strong>
    <%= event.description %>
  </p>
  <p>
    <strong>Date</strong>
    <%= event.date_time %>
  </p>
  <%= link_to 'Show Event', event_path(event) %><br>

<% end %>
<hr>
 

<div>
  <h1>Upcoming Events</h1>
  <div class="grid-container">

  <% @upcoming_events.each do |event| %> 
  <div class="grid-item">
    <p> <%= event.description %> </p>
    <p>Date: <%= event.date_time %> </p>
  </div>
  <% end %>
  
  </div>
</div>

<hr>

<div>
  <h1>Past Events</h1>
  <div class="grid-container">

  <% @past_events.each do |event| %> 
  <div class="grid-item">
    <p> <%= event.description %> </p>
    <p>Date: <%= event.date_time %> </p>
  </div>
  <% end %>
  
  </div>
</div>


 </div>